apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spiderpool
resources:
- nfr.yaml
- hca1.yaml
- hca2.yaml
- hca3.yaml
- hca4.yaml
- hca5.yaml
- hca6.yaml
- hca7.yaml
- hca8.yaml
